name: Deploy to EC2

on:
  push:
    branches:
      - 'qa'


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: qa

    steps:
      - name: creating pem file
        run: |
          echo "${PEM_FILE}" > talking-works-qa.pem
        env:
          PEM_FILE: ${{ secrets.QA_PEM_FILE }}

      - name: login into ec2 and automating the script
        run: |
          chmod 600 talking-works-qa.pem
          ssh -tt -i talking-works-qa.pem -o StrictHostKeyChecking=no ${{ secrets.QA_EC2_USER }}@${{ secrets.QA_EC2_HOST }} << 'EOF'
            
            cd talking-works-qa/
            cd database-docker/

            
            git checkout qa
            git pull origin qa
            
            docker stop database-docker
            docker rm database-docker
            docker rmi database-docker:latest
            
            docker build -t database-docker:latest .
            docker run \
            -p 5432:5432 --name database-docker  \
            --network ${{secrets.QA_BACKEND_NETWORK}} \
            -d service-discovery:latest \
            -v pgdata:/var/lib/postgresql/data \
          
            exit
          EOF